/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mvcdemo;

/**
 *
 * @author user
 */
public class CircleController extends javax.swing.JPanel {
    private CircleModel model;
    /**
     * Creates new form CircleController
     */
    public CircleController() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfRadius = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jcboFilled = new javax.swing.JComboBox();

        jLabel1.setText("Radius:");

        jtfRadius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfRadiusActionPerformed(evt);
            }
        });

        jLabel2.setText("Filled:");

        jcboFilled.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "false", "true" }));
        jcboFilled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboFilledActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcboFilled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfRadius, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfRadius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcboFilled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(198, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfRadiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfRadiusActionPerformed
        // TODO add your handling code here:
        if (getModel() != null) // Set radius in the model 
          getModel().setRadius(Double.parseDouble(jtfRadius.getText()));
    }//GEN-LAST:event_jtfRadiusActionPerformed

    private void jcboFilledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboFilledActionPerformed
        // TODO add your handling code here:
        if (getModel() != null) // Set filled property value in the model
          getModel().setFilled((jcboFilled.getSelectedItem()).toString().equals("true"));
    }//GEN-LAST:event_jcboFilledActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox jcboFilled;
    private javax.swing.JTextField jtfRadius;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the model
     */
    public CircleModel getModel() {
        return model;
    }

    /**
     * @param model the model to set
     */
    public void setModel(CircleModel model) {
        this.model = model;
    }
}
